### ISSUE TITLE
Filter by Agency

### ISSUE THREAD

**Issue by brigsz** [agrc/BEMS#24]
A user needs to filter by agency and see the agency boundary on the screen

**Comment by steveoh** [comment]
This is what the `EMSServiceAreas` data has
![image](https://cloud.githubusercontent.com/assets/325813/6363723/de70e768-bc59-11e4-8d4b-0fc666c50168.png)

Do I need to be made aware of another feature class that has agency boundaries?

**Comment by brigsz** [comment]
Mmmmm. Sounds like I need to investigate further.

**Comment by brigsz** [comment]
We may need to look at this together as health.EMSServiceAreas has a name field in it.  so I am confused as to what layer you are referencing in your last comment.

**Comment by steveoh** [comment]
We are talking about the same layer. The schema fooled me. I was looking for agency, but name works. Thanks for clarifying.
