### ISSUE TITLE
Instructions for usage of Application

### ISSUE THREAD

**Issue by brigsz** [agrc/BEMS#27]
BEMS staff will write this, with suggestions from AGRC

**Comment by steveoh** [comment]
has this been written?

**Comment by brigsz** [comment]
Nope, I will do that with the client when everything is complete



On Jul 29, 2015, at 11:27 AM, steveoh <notifications@github.com> wrote:

has this been written?

—
Reply to this email directly or view it on GitHub
<https://github.com/agrc/BEMS/issues/27#issuecomment-126027385>.

**Comment by brigsz** [comment]
This is the help doc. for the link.  I will see if I have where they wanted it.


[AGRC Map Guide.pdf](https://github.com/agrc/BEMS/files/10314/AGRC.Map.Guide.pdf)
