### ISSUE TITLE
Switch out names/attributes

### ISSUE THREAD

**Issue by brigsz** [agrc/BEMS#35]
`License/Designation Type`(boundaries)
1. Quick Response/Rescue = 911 Response without Transport
2. Ground Ambulance = 911 Response with Transport
3. Paramedic Rescue = Rescue
4. Paramedic Ground Ambulance = 911 Response with Transport
5. Interfacility = Medical Transport
6. NEW = Air Medical

`Service Levels`

1. Basic = EMT-Basic
2. Intermediate = EMT-Intermediate
3. Intermediate Advanced = 2009 AEMT
4. Paramedic = 2009 Paramedic
5. NEW = First Responder
6. NEW = Nurse

**Comment by brigsz** [comment]
I know I need to change these in the data, do all the widgets and tools in the app that need this info get it from the feature class?

**Comment by steveoh** [comment]
[No](https://github.com/agrc/BEMS/blob/master/src/app/data/serviceLevels.js), [they](https://github.com/agrc/BEMS/blob/master/src/app/data/serviceTypes.js) do not get them from the feature class.

**Comment by steveoh** [comment]
I took a stab at the new mxd.
